### PR TITLE
Compiling fix for Vulnerable Regular Expression into updated list

### PR DESCRIPTION
**Pull request by PenguinOfWar**
As @magesh0819 mentioned in his [comment](https://github.com/esamattis/underscore.string/issues/510#issuecomment-501031057) on #510 this fixes the issue with the ReDoS vulnerable regex by rebuilding the dist files.

This package should be redeployed to npm after merge.

### CODE REVIEW

**Comment by tomasAlabes** [comment]
@esamattis could you please merge this to fix the ReDos vulnerability?

**Comment by rustybailey** [comment]
@esamattis Is it possible for this to get merged? This is causing grunt to have an indirect vulnerability. See https://snyk.io/test/npm/grunt/1.4.0.

**Comment by adammy123** [comment]
@stoeffel can you help to merge this?

**Comment by esamattis** [comment]
3.3.6 is out with this.

**Comment by rustybailey** [comment]
@esamattis It looks like Snyk is reporting that this vulnerability still exists in 3.3.6: https://snyk.io/vuln/npm:underscore.string

**Comment by esamattis** [comment]
Hmph, wonder what's missing 🤔

**Comment by carneam** [comment]
looks like Synk did update the latest update and it shows 3.3.6 does not have any vulnerabilities. Thanks Esa!

**Comment by rustybailey** [comment]
Thanks for confirming that @carneam. Looks like grunt 1.4.0 was also updated to have 0 vulnerabilities. See: https://snyk.io/vuln/npm:grunt.

**Pull request closed without merging**
